const countries = [
    { id: 1, name: "Afghanistan" },
    { id: 2, name: "Albania" },
    { id: 3, name: "Algeria" },
    { id: 4, name: "Andorra" },
    { id: 5, name: "Angola" },
    { id: 6, name: "Antigua and Barbuda" },
    { id: 7, name: "Argentina" },
    { id: 8, name: "Armenia" },
    { id: 9, name: "Australia" },
    { id: 10, name: "Austria" },
    { id: 11, name: "Azerbaijan" },
    { id: 12, name: "Bahamas" },
    { id: 13, name: "Bahrain" },
    { id: 14, name: "Bangladesh" },
    { id: 15, name: "Barbados" },
    { id: 16, name: "Belarus" },
    { id: 17, name: "Belgium" },
    { id: 18, name: "Belize" },
    { id: 19, name: "Benin" },
    { id: 20, name: "Bhutan" },
    { id: 120, name: "Venezuela" },
    { id: 21, name: "Bolivia" },
    { id: 22, name: "Bosnia and Herzegovina" },
    { id: 23, name: "Botswana" },
    { id: 24, name: "Brazil" },
    { id: 25, name: "Brunei" },
    { id: 26, name: "Bulgaria" },
    { id: 27, name: "Burkina Faso" },
    { id: 28, name: "Burundi" },
    { id: 29, name: "Cabo Verde" },
    { id: 30, name: "Cambodia" },
    { id: 30, name: "Ivory Cost" },
    { id: 31, name: "Cameroon" },
    { id: 32, name: "Canada" },
    {
        id: 33,
        name: "Central African Republic",
    },
    { id: 34, name: "Chad" },
    { id: 35, name: "Chile" },
    { id: 36, name: "China" },
    { id: 37, name: "Colombia" },
    { id: 38, name: "Comoros" },
    { id: 39, name: "Congo" },
    { id: 40, name: "Costa Rica" },
    { id: 41, name: "Croatia" },
    { id: 42, name: "Cuba" },
    { id: 43, name: "Cyprus" },
    { id: 44, name: "Czech Republic" },
    {
        id: 45,
        name: "Democratic Republic of the Congo",
    },
    { id: 46, name: "Denmark" },
    { id: 47, name: "Djibouti" },
    { id: 48, name: "Dominica" },
    { id: 49, name: "Dominican Republic" },
    { id: 50, name: "Ecuador" },
    { id: 51, name: "Egypt" },
    { id: 52, name: "El Salvador" },
    { id: 53, name: "Equatorial Guinea" },
    { id: 54, name: "Eritrea" },
    { id: 55, name: "Estonia" },
    { id: 56, name: "Eswatini" },
    { id: 57, name: "Ethiopia" },
    { id: 58, name: "Fiji" },
    { id: 59, name: "Finland" },
    { id: 60, name: "France" },
    { id: 61, name: "Gabon" },
    { id: 62, name: "Gambia" },
    { id: 63, name: "Georgia" },
    { id: 64, name: "Germany" },
    { id: 65, name: "Ghana" },
    { id: 66, name: "Greece" },
    { id: 67, name: "Grenada" },
    { id: 68, name: "Guatemala" },
    { id: 69, name: "Guinea" },
    { id: 70, name: "Guinea-Bissau" },
    { id: 71, name: "Guyana" },
    { id: 72, name: "Haiti" },
    { id: 73, name: "Holy See" },
    { id: 74, name: "Honduras" },
    { id: 75, name: "Hungary" },
    { id: 76, name: "Iceland" },
    { id: 77, name: "India" },
    { id: 78, name: "Indonesia" },
    { id: 79, name: "Iran" },
    { id: 80, name: "Iraq" },
    { id: 81, name: "Ireland" },
    { id: 82, name: "Israel" },
    { id: 83, name: "Italy" },
    { id: 84, name: "Jamaica" },
    { id: 85, name: "Japan" },
    { id: 86, name: "Jordan" },
    { id: 87, name: "Kazakhstan" },
    { id: 88, name: "Kenya" },
    { id: 89, name: "Kiribati" },
    { id: 90, name: "Kuwait" },
    { id: 91, name: "Kyrgyzstan" },
    { id: 92, name: "Laos" },
    { id: 93, name: "Latvia" },
    { id: 94, name: "Lebanon" },
    { id: 95, name: "Lesotho" },
    { id: 96, name: "Liberia" },
    { id: 97, name: "Libya" },
    { id: 98, name: "Liechtenstein" },
    { id: 99, name: "Lithuania" },
    { id: 100, name: "Luxembourg" },
    { id: 101, name: "Madagascar" },
    { id: 102, name: "Malawi" },
    { id: 103, name: "Malaysia" },
    { id: 104, name: "Maldives" },
    { id: 105, name: "Mali" },
    { id: 106, name: "Malta" },
    { id: 107, name: "Marshall Islands" },
    { id: 108, name: "Mauritania" },
    { id: 109, name: "Mauritius" },
    { id: 110, name: "Mexico" },
    { id: 111, name: "Micronesia" },
    { id: 112, name: "Moldova" },
    { id: 113, name: "Monaco" },
    { id: 114, name: "Mongolia" },
    { id: 115, name: "Montenegro" },
    { id: 116, name: "Morocco" },
    { id: 117, name: "Mozambique" },
    { id: 118, name: "Myanmar" },
    { id: 119, name: "Namibia" },
    { id: 120, name: "Nauru" },
    { id: 121, name: "Nepal" },
    { id: 122, name: "Netherlands" },
    { id: 123, name: "New Zealand" },
    { id: 124, name: "Nicaragua" },
    { id: 125, name: "Niger" },
    { id: 126, name: "Nigeria" },
    { id: 127, name: "North Korea" },
    { id: 128, name: "North Macedonia" },
    { id: 129, name: "Norway" },
    { id: 130, name: "Oman" },
    { id: 131, name: "Pakistan" },
    { id: 132, name: "Palau" },
    { id: 133, name: "Panama" },
    { id: 134, name: "Papua New Guinea" },
    { id: 135, name: "Paraguay" },
    { id: 136, name: "Peru" },
    { id: 137, name: "Philippines" },
    { id: 138, name: "Poland" },
    { id: 139, name: "Portugal" },
    { id: 140, name: "Qatar" },
    { id: 141, name: "Romania" },
    { id: 142, name: "Russia" },
    { id: 143, name: "Rwanda" },
    { id: 144, name: "Saint Kitts and Nevis" },
    { id: 145, name: "Saint Lucia" },
    {
        id: 146,
        name: "Saint Vincent and the Grenadines",
    },
    { id: 147, name: "Samoa" },
    { id: 148, name: "San Marino" },
    { id: 149, name: "Sao Tome and Principe" },
    { id: 150, name: "Saudi Arabia" },
    { id: 151, name: "Senegal" },
    { id: 152, name: "Serbia" },
    { id: 153, name: "Seychelles" },
    { id: 154, name: "Sierra Leone" },
    { id: 155, name: "Singapore" },
    { id: 156, name: "Slovakia" },
    { id: 157, name: "Slovenia" },
    { id: 158, name: "Solomon Islands" },
    { id: 159, name: "Somalia" },
    { id: 160, name: "South Africa" },
    { id: 161, name: "South Korea" },
    { id: 162, name: "South Sudan" },
    { id: 163, name: "Spain" },
    { id: 164, name: "Sri Lanka" },
    { id: 165, name: "Sudan" },
    { id: 166, name: "Suriname" },
    { id: 167, name: "Sweden" },
    { id: 168, name: "Switzerland" },
    { id: 169, name: "Syria" },
    { id: 170, name: "Tajikistan" },
    { id: 171, name: "Tanzania" },
    { id: 172, name: "Thailand" },
    { id: 173, name: "Timor-Leste" },
    { id: 174, name: "Togo" },
    { id: 175, name: "Tonga" },
    { id: 176, name: "Trinidad and Tobago" },
    { id: 177, name: "Tunisia" },
    { id: 178, name: "Turkey" },
    { id: 179, name: "Turkmenistan" },
    { id: 180, name: "Tuvalu" },
    { id: 181, name: "Uganda" },
    { id: 182, name: "Ukraine" },
    { id: 183, name: "United Arab Emirates" },
    { id: 184, name: "United Kingdom" },
    { id: 185, name: "United States" },
    { id: 186, name: "Uruguay" },
    { id: 187, name: "Uzbekistan" },
    { id: 188, name: "Vanuatu" },
    { id: 189, name: "Vatican City" },
    { id: 190, name: "Venezuela" },
    { id: 191, name: "Vietnam" },
    { id: 192, name: "Yemen" },
    { id: 193, name: "Zambia" },
    { id: 194, name: "Zimbabwe" },
];

const listArray = [
    {
        id: 1,
        text: "High School",
        link: "https://res.cloudinary.com/highereducation/image/upload/co_rgb:e22944,e_colorize:100,f_auto,fl_lossy,q_auto,h_48,w_48/v1/Voyager/signal1",
    },
    {
        id: 2,
        text: "GED",
        link: "https://res.cloudinary.com/highereducation/image/upload/co_rgb:e22944,e_colorize:100,f_auto,fl_lossy,q_auto,h_48,w_48/v1/Voyager/signal1",
    },
    {
        id: 3,
        text: "Associate",
        link: "https://res.cloudinary.com/highereducation/image/upload/co_rgb:e22944,e_colorize:100,f_auto,fl_lossy,q_auto,h_48,w_48/v1/Voyager/signal2",
    },
    {
        id: 4,
        text: "Bachelor's",
        link: "https://res.cloudinary.com/highereducation/image/upload/co_rgb:e22944,e_colorize:100,f_auto,fl_lossy,q_auto,h_48,w_48/v1/Voyager/signal2",
    },
    {
        id: 5,
        text: "Master's",
        link: "https://res.cloudinary.com/highereducation/image/upload/co_rgb:e22944,e_colorize:100,f_auto,fl_lossy,q_auto,h_48,w_48/v1/Voyager/signal4",
    },
    {
        id: 6,
        text: "Doctorate",
        link: "https://res.cloudinary.com/highereducation/image/upload/co_rgb:e22944,e_colorize:100,f_auto,fl_lossy,q_auto,h_48,w_48/v1/Voyager/signal5",
    },
    {
        id: 7,
        text: "Diploma",
        link: "https://res.cloudinary.com/highereducation/image/upload/co_rgb:e22944,e_colorize:100,f_auto,fl_lossy,q_auto,h_48,w_48/v1/Voyager/signal5",
    },
];

export { countries, listArray };
